name: Q3 workflow
run-name:   Q3 Workflow
on: [push]
permissions: 
  contents: write
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: XXX teste creation nouveau fichier
        run: |
          echo "Nom : Sacha Baltide" > Q3_archive_java.txt
          echo "Contenu de Q3.java :" >> Q2_archive_README.md
          cat Q3.java >> Q2_archive_README.md
    # push
      - name: ajout du nom du user
        run: |
          git config --global user.name Saytolecrack
      - name: ajout du mail du user
        run: |
          git config --global user.email sachat.baltide@etu.univ-lehavre.fr
      - name: ajout de l archive dans github
        run: |
          git add Q3_archive_java.txt
      - name: commit
        run: | 
          git commit -m "Add Q3_archive_java.txt avec contenu mis a jour"
      - name: push l archive dans le repository
        run: |
           git push
